import type { Station } from "@/src/types";

export const ROUTES = {
  home: "/",
  emergency: "/emergency",
  planTrip: "/plan-trip",
  costComparison: "/cost-comparison",
  evDatabase: "/ev-database",
  stations: "/charging-stations",
  profile: "/profile",
  login: "/login",
  signup: "/signup",
  forgotPassword: "/forgot-password",
  authCallback: "/auth/callback",
  authVerify: "/auth/verify",
  authResetPassword: "/auth/reset-password",
} as const;

export const AUTH_STORAGE_KEY = "ev-auth-session";
export const AUTH_COOKIE_NAME = "ev_session_mode";
export const LEGACY_AUTH_COOKIE_NAME = "ev_auth_mode";

export const EMERGENCY_CONTACTS = [
  {
    label: "Rescue 1122",
    number: "1122",
    description: "Ambulance, rescue, and fire emergency response.",
  },
  {
    label: "Motorway Police",
    number: "130",
    description: "Roadside help and towing support on national highways and motorways.",
  },
  {
    label: "Police Emergency",
    number: "15",
    description: "Immediate police assistance in Pakistan.",
  },
  {
    label: "Edhi Ambulance",
    number: "115",
    description: "Private ambulance support where available.",
  },
] as const;

export const COPY = {
  unavailableMap: "Add a Google Maps API key to view the interactive map.",
  noStations: "No charging stations found. Try another location.",
  directionsUnavailable: "Directions are unavailable for this station.",
  apiUnavailable: "Station data is temporarily unavailable.",
} as const;

export const SAMPLE_STATIONS: Station[] = [
  {
    id: "lahore-cantt-ev",
    google_place_id: "ChIJAweL70AFGTkRGEQySEB7Fgw",
    name: "Electric Vehicle Charging Station",
    address: "Girja Chowk, Cantt, Lahore, Pakistan",
    latitude: 31.5222391,
    longitude: 74.3797271,
    phone: "+92 306 5545684",
    website: "https://maps.google.com",
    rating: 4.1,
    operator: "Private Operator",
    created_at: null,
    updated_at: null,
  },
  {
    id: "lahore-packages-mall-ev",
    google_place_id: "ChIJcVptdQAHGTkR9Zvx3vQ7J9M",
    name: "Electric Vehicle Charging Station",
    address: "Packages Mall, Nishtar Town, Lahore, Pakistan",
    latitude: 31.4729758,
    longitude: 74.3558348,
    phone: null,
    website: "https://maps.google.com",
    rating: 3.5,
    operator: "Private Operator",
    created_at: null,
    updated_at: null,
  },
  {
    id: "lahore-bmw-gulberg-ev",
    google_place_id: "ChIJSZvkrP8EGTkRhJqIEazigfM",
    name: "BMW Destination Charging Station",
    address: "25 Gurumangat Rd, Block N Gulberg III, Lahore",
    latitude: 31.52273,
    longitude: 74.35634,
    phone: "+92 305 2099323",
    website: "https://maps.google.com",
    rating: 2.5,
    operator: "BMW",
    created_at: null,
    updated_at: null,
  },
  {
    id: "lahore-bmw-davis-road-ev",
    google_place_id: "ChIJ86NFzssEGTkRf07gpGvnsss",
    name: "BMW PHEV Charging Station",
    address: "15 Davis Road, Garhi Shahu, Lahore, Pakistan",
    latitude: 31.5576398,
    longitude: 74.3387157,
    phone: "+92 42 36360265",
    website: "https://maps.google.com",
    rating: 4.2,
    operator: "Dewan Motors (BMW)",
    created_at: null,
    updated_at: null,
  },
  {
    id: "lahore-johar-town-ev",
    google_place_id: "ChIJO9mjBAABGTkRn3h2VhV9r74",
    name: "Electric Vehicle Charging Station",
    address: "Samsani Rd, Block F1 Phase 1 Johar Town, Lahore, Pakistan",
    latitude: 31.4627352,
    longitude: 74.2779871,
    phone: null,
    website: "https://maps.google.com",
    rating: 5.0,
    operator: "Private Operator",
    created_at: null,
    updated_at: null,
  },
  {
    id: "lahore-go-green-packages-mall-ev",
    google_place_id: "ChIJ3XVluc4HGTkRu5QorXb8bnY",
    name: "Go Green Avenue Packages Mall Charging Station",
    address: "Entrance 3, Packages Mall, Walton Rd, Lahore, Pakistan",
    latitude: 31.4717376,
    longitude: 74.3560398,
    phone: "+92 308 4901271",
    website: "https://maps.google.com",
    rating: 4.4,
    operator: "Go Green Avenue",
    created_at: null,
    updated_at: null,
  },
  {
    id: "lahore-a-charge-thokar-ev",
    google_place_id: "ChIJDZ3DVhIDGTkRFr6MrSxMQVo",
    name: "A-Charge Charging Station",
    address: "Metro Thokar Niaz Baig, Amarkot, Lahore, Pakistan",
    latitude: 31.4671779,
    longitude: 74.2353592,
    phone: "+92 306 0651874",
    website: "https://maps.google.com",
    rating: 3.9,
    operator: "A-Charge",
    created_at: null,
    updated_at: null,
  },
  {
    id: "lahore-go-green-gulberg-ev",
    google_place_id: "ChIJaVpDlhUFGTkRdeW21dpyyvk",
    name: "Go Green Avenue Charging Station",
    address: "126 E-1, 111 Main Boulevard Gulberg III, Lahore",
    latitude: 31.5144751,
    longitude: 74.3425052,
    phone: "+92 311 1164641",
    website: "https://maps.google.com",
    rating: 4.8,
    operator: "Go Green Avenue",
    created_at: null,
    updated_at: null,
  },
  {
    id: "lahore-go-green-packages-2-ev",
    google_place_id: "ChIJ3Vb0XQAHGTkRHH9LQu0XPmQ",
    name: "Go Green Charging Station",
    address: "Packages Mall, Walton Rd, Nishtar Town, Lahore, Pakistan",
    latitude: 31.471531,
    longitude: 74.3557953,
    phone: "+92 308 4901271",
    website: "https://maps.google.com",
    rating: 5.0,
    operator: "Go Green Avenue",
    created_at: null,
    updated_at: null,
  },
  {
    id: "lahore-nishat-colony-ev",
    google_place_id: "ChIJsVjWPwAFGTkRTjs7DH4VmII",
    name: "Electric Vehicle Charging Station",
    address: "Keer Rd, Nishat Colony, Lahore, Pakistan",
    latitude: 31.4943161,
    longitude: 74.3960572,
    phone: null,
    website: "https://maps.google.com",
    rating: 4.3,
    operator: "Private Operator",
    created_at: null,
    updated_at: null,
  },
  {
    id: "islamabad-blue-area-ev",
    google_place_id: "sample-islamabad-blue-area",
    name: "Blue Area EV Charging Hub",
    address: "Blue Area, Islamabad",
    latitude: 33.7136,
    longitude: 73.0639,
    phone: null,
    website: "https://maps.google.com",
    rating: 4.1,
    operator: "Sample Network",
    created_at: null,
    updated_at: null,
  },
  {
    id: "bhera-m2-ev",
    google_place_id: null,
    name: "Bhera M-2 EV Charging Station",
    address: "M-2 Motorway, outside Bhera toll plaza, Punjab, Pakistan",
    latitude: 32.463068736919496,
    longitude: 72.88432014721543,
    phone: "+92 307 6559293",
    website: "https://openchargemap.org/poi/details/479904",
    rating: null,
    operator: "Motorway charging network",
    created_at: null,
    updated_at: null,
  },
  {
    id: "karachi-clifton-ev",
    google_place_id: "sample-karachi-clifton",
    name: "Clifton EV Charger",
    address: "Block 5 Clifton, Karachi",
    latitude: 24.8138,
    longitude: 67.0305,
    phone: null,
    website: "https://maps.google.com",
    rating: 4.0,
    operator: "Sample Operator",
    created_at: null,
    updated_at: null,
  },
];
