import type { IconType } from "react-icons";
import {
  MdArrowBack,
  MdArrowForward,
  MdBatteryChargingFull,
  MdBolt,
  MdCalculate,
  MdCampaign,
  MdCheck,
  MdChevronRight,
  MdClose,
  MdCompareArrows,
  MdDirectionsCar,
  MdEdit,
  MdElectricCar,
  MdEmergency,
  MdEnergySavingsLeaf,
  MdEvStation,
  MdExpandMore,
  MdFlag,
  MdGroups,
  MdHome,
  MdLocalCafe,
  MdLocalGasStation,
  MdLocalParking,
  MdLocationOn,
  MdLogout,
  MdMarkEmailRead,
  MdMenu,
  MdMosque,
  MdMyLocation,
  MdNearMe,
  MdPersonAdd,
  MdPhotoCamera,
  MdPower,
  MdReadMore,
  MdRestaurant,
  MdRoute,
  MdSchedule,
  MdShield,
  MdSpeed,
  MdTune,
  MdWc,
} from "react-icons/md";

const icons: Record<string, IconType> = {
  arrow_back: MdArrowBack,
  arrow_forward: MdArrowForward,
  battery_charging_full: MdBatteryChargingFull,
  bolt: MdBolt,
  calculate: MdCalculate,
  campaign: MdCampaign,
  check: MdCheck,
  chevron_right: MdChevronRight,
  close: MdClose,
  conversion_path: MdCompareArrows,
  directions_car: MdDirectionsCar,
  edit: MdEdit,
  electric_bolt: MdBolt,
  electric_car: MdElectricCar,
  emergency: MdEmergency,
  energy_savings_leaf: MdEnergySavingsLeaf,
  ev_station: MdEvStation,
  expand_more: MdExpandMore,
  flag: MdFlag,
  groups: MdGroups,
  home: MdHome,
  local_cafe: MdLocalCafe,
  local_gas_station: MdLocalGasStation,
  local_parking: MdLocalParking,
  location_on: MdLocationOn,
  logout: MdLogout,
  mark_email_read: MdMarkEmailRead,
  menu: MdMenu,
  mosque: MdMosque,
  my_location: MdMyLocation,
  near_me: MdNearMe,
  person_add: MdPersonAdd,
  photo_camera: MdPhotoCamera,
  power: MdPower,
  read_more: MdReadMore,
  restaurant: MdRestaurant,
  route: MdRoute,
  schedule: MdSchedule,
  shield: MdShield,
  speed: MdSpeed,
  tune: MdTune,
  wc: MdWc,
};

export function AppIcon({
  name,
  className,
}: {
  name: string;
  className?: string;
}) {
  const Icon = icons[name] || MdBolt;

  return <Icon className={className} aria-hidden="true" focusable="false" />;
}
